name = "PYTHONOMANIA"
description = "Discover the world of Python at PYTHONOMANIA!"
keywords = "python, programming, coding"
image = "logo.jpg"
theme = "dark"
primary_color = "#13a7d4"
text_align = "center"
gtag_id = "G-33WB8LVHR6"
base_url = "https://pythonomania.github.io"

[[sections]]
title = "Test section"
description = "Test"
direction = "column"
item_style = "outline"
[[sections.items]]
title = "test"
description = "test"
url = ""


[[sections]]
title = "Links"
description = ""
direction = "row"
item_style = "filled"
[[sections.items]]
title = "Telegram"
url = "https://t.me/PYTHONOMANIA"
[[sections.items]]
title = "Donate"
url = "https://t.me/tribute/app?startapp=d6uY"
