name = "PYTHONOMANIA"
description = "Discover the world of Python at PYTHONOMANIA!"
keywords = "python, programming, coding"
image = "logo.jpg"
theme = "dark"
primary_color = "#13a7d4"
text_align = "center"
gtag_id = "G-33WB8LVHR6"
base_url = "https://pythonomania.github.io"

[[sections]]
title = "Sample apps"
description = "Discover some of the apps we’ve built to simplify tasks and demonstrate the versatility of Python:"
direction = "column"
item_style = "outline"
[[sections.items]]
title = "Weather app"
description = "Stay informed about the latest weather conditions in your area or any location worldwide. This app uses a free weather API to provide real-time updates, including temperature, humidity, and weather descriptions, all displayed with an intuitive and visually appealing interface. Perfect for planning your day or tracking conditions on the go!"
url = "https://pyweatherapp.streamlit.app/"
[[sections.items]]
title = "OCR app"
description = "Extract text from images and PDFs with ease!
Turn scanned documents, images, or PDFs into editable text effortlessly. This app leverages Tesseract OCR and modern libraries to provide accurate text recognition in multiple languages, including Russian. Includes a progress bar for seamless tracking of processing tasks and supports various file formats like JPG, PNG, and PDF."
url = "https://ocrtestapp.streamlit.app/"


[[sections]]
title = "Links"
description = ""
direction = "row"
item_style = "filled"
[[sections.items]]
title = "Telegram"
url = "https://t.me/PYTHONOMANIA"
[[sections.items]]
title = "Donate"
url = "https://t.me/tribute/app?startapp=d6uY"
