name = "PYTHONOMANIA"
description = "Discover the world of Python at PYTHONOMANIA!"
keywords = "python, programming, coding"
image = "logo.jpg"
theme = "dark"
primary_color = "#13a7d4"
text_align = "center"
gtag_id = "G-33WB8LVHR6"
base_url = "https://pythonomania.github.io"

[[sections]]
title = "Sample apps"
description = "---"
direction = "column"
item_style = "outline"
[[sections.items]]
title = "Weather app"
description = "weather app"
url = "https://pyweatherapp.streamlit.app/"
[[sections.items]]
title = "OCR app"
description = "Pdf to text convertion"
url = "https://ocrtestapp.streamlit.app/"


[[sections]]
title = "Links"
description = ""
direction = "row"
item_style = "filled"
[[sections.items]]
title = "Telegram"
url = "https://t.me/PYTHONOMANIA"
[[sections.items]]
title = "Donate"
url = "https://t.me/tribute/app?startapp=d6uY"
